In [1]:
import numpy as np

# Array

In [12]:
arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr1.dtype, type(arr1)

(dtype('int64'), numpy.ndarray)

In [16]:
print(arr1[0])
print(arr1[3])
print(arr1[-1])

[1 2 3]
[10 11 12]
[10 11 12]


In [5]:
list1 = [[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [7]:
print(list1[0][0])

1


In [15]:
print(arr1[0,0])
print(arr1[0])
print(arr1[:, 0])
print(arr1[:])

1
[1 2 3]
[ 1  4  7 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
arr2 = np.array([[.1, .2],[.3, .4]])
print(arr2)
print(arr2.dtype)

[[0.1 0.2]
 [0.3 0.4]]
float64


In [19]:
arr1.shape

(4, 3)

In [20]:
arr2.ndim

2

In [21]:
arr3 = np.array([
    [
        [1, 2, 3],
        [11, 22, 33]
    ],
    [
        [4, 5, 6],
        [44, 55, 66]
    ]
])
print(arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [23]:
print("shape: ", arr3.shape)
print("dim: ", arr2.ndim)

shape:  (2, 2, 3)
dim:  2


In [42]:
arr_zeros_1 = np.zeros(10)
arr_zeros_2 = np.zeros((10,5))
arr_zeros_3 = np.zeros([5, 10, 10])
arr_zeros_4 = np.zeros(10)

In [27]:
arr_empty = np.empty((1000,1000))
print(arr_empty)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
arr_random = np.randin

AttributeError: module 'numpy' has no attribute 'randin'

In [30]:
range(0, 100, 2)

range(0, 100, 2)

In [33]:
print(np.arange(0, 100, 2))
print(np.arange(10))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
arr_one = np.array([1, 2, 3, 4, 5])

np.append(arr1, [[13, 14, 5]], axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14,  5]])

In [38]:
np.append(arr1, [[13], [14], [15], [16]], axis=1)

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [ ]:
# parameter axis = dimensi
# untuk selain axis haru dipastikan ukurannya sama
# cek shape

In [51]:
arr_ones_3 = np.ones((1,10,10))

In [52]:
np.append(arr_ones_3, np.zeros(1,10,10), axis = 0)

TypeError: Cannot interpret '10' as a data type

In [54]:
arr_12 = np.arange(12) + 1
print(arr_12)

np.delete(arr1, 2, axis=1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [55]:
np.delete(arr1, 2, axis=1)

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [57]:
arr_unsorted = np.array([3, 6, 1, 56, 1, 0])
print(arr_unsorted)
np.sort(arr_unsorted)

[ 3  6  1 56  1  0]


array([ 0,  1,  1,  3,  6, 56])

In [59]:
print(arr1)
np.sort(arr1, axis =-1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
arr1[0] = [5, 11, 10]
arr1

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
print(np.sort(arr1))
print(np.sort(arr1, axis=0))

[[ 5 10 11]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 5  8  9]
 [ 7 11 10]
 [10 11 12]]


In [63]:
arr_one.shape, arr1.shape

((5,), (4, 3))

In [64]:
arr_one

array([1, 2, 3, 4, 5])

In [65]:
arr1

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
vector_col = np.array([[1], [2], [3], [4], [5]])
print(vector_col, vector_col.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [69]:
#jumlah elemen / size harus sama 
np.reshape(arr1, (3, 4))

array([[ 5, 11, 10,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
arr1
arr1.shape

(4, 3)

In [71]:
np.reshape(arr1, (2, 6))

array([[ 5, 11, 10,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [84]:
print(np.reshape(arr1, (2, 2, 3)))

print(np.reshape(arr1, (1, 12)))

print(np.reshape(arr1, (4, 1, 3)))

[[[ 5 11 10]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 5 11 10  4  5  6  7  8  9 10 11 12]]
[[[ 5 11 10]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [76]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [80]:
arr1[:, np.newaxis]

array([[[ 5, 11, 10]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [81]:
arr1[:, :, np.newaxis]

array([[[ 5],
        [11],
        [10]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [82]:
arr1[..., np.newaxis]

array([[[ 5],
        [11],
        [10]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [85]:
arr1[arr1 > 5]

array([11, 10,  6,  7,  8,  9, 10, 11, 12])

In [86]:
arr1.flatten()

array([ 5, 11, 10,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
arr1[(arr1 % 2 == 0) & (arr1 > 5)]

array([10,  6,  8, 10, 12])

In [90]:
arr1[(arr1 % 2 == 0) | (arr1 > 5)]

array([11, 10,  4,  6,  7,  8,  9, 10, 11, 12])

In [91]:
np.expand_dims(arr1, axis=0)

array([[[ 5, 11, 10],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
np.concatenate((arr1, arr1))

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
np.concatenate((arr1, arr1), axis=1)

array([[ 5, 11, 10,  5, 11, 10],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [94]:
arr1.sum(), np.sum(arr1), sum(arr1)

(98, 98, array([26, 35, 37]))

In [95]:
arr1.sum(axis=0)

array([26, 35, 37])

In [96]:
arr1.std()

2.6087459737497545

In [98]:
arr1.mean()

8.166666666666666

In [99]:
arr1.min()

4

In [100]:
arr1.max()

12

In [107]:
arr11 = arr1 * 10

In [108]:
print(arr1 + arr11)

[[ 55 121 110]
 [ 44  55  66]
 [ 77  88  99]
 [110 121 132]]


In [109]:
arr1.dot(arr11.T)

array([[2460, 1350, 2130, 2910],
       [1350,  770, 1220, 1670],
       [2130, 1220, 1940, 2660],
       [2910, 1670, 2660, 3650]])

In [110]:
np.multiply(arr1, arr11)

array([[ 250, 1210, 1000],
       [ 160,  250,  360],
       [ 490,  640,  810],
       [1000, 1210, 1440]])

Preview

In [17]:
array_1 = np.arange(0, 1, 5e-2)[:,None]
print(array_1, array_1.shape)

# Reshape
array_2 = array_1.reshape(10,2)
print(array_2, array_2.shape)

# 2 time prev arr
array_3 = array_1
array_4 = array_3.dot(2)
print(array_3.shape, array_3 * 2)

mm = np.matmul(array_3, array_4.T)
# mean
mm_mean = mm.mean(axis=0)
print(mm_mean)
print(mm[:, -1].mean())

#median
mm_median = np.median(mm, axis=0)
print(mm_median)

#std
mm_std = mm.std(axis=0)
print(mm_std)

#var
mm_var = mm.var(axis=0)
print(mm_var)

[[0.  ]
 [0.05]
 [0.1 ]
 [0.15]
 [0.2 ]
 [0.25]
 [0.3 ]
 [0.35]
 [0.4 ]
 [0.45]
 [0.5 ]
 [0.55]
 [0.6 ]
 [0.65]
 [0.7 ]
 [0.75]
 [0.8 ]
 [0.85]
 [0.9 ]
 [0.95]] (20, 1)
[[0.   0.05]
 [0.1  0.15]
 [0.2  0.25]
 [0.3  0.35]
 [0.4  0.45]
 [0.5  0.55]
 [0.6  0.65]
 [0.7  0.75]
 [0.8  0.85]
 [0.9  0.95]] (10, 2)
(20, 1) [[0. ]
 [0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]
 [0.7]
 [0.8]
 [0.9]
 [1. ]
 [1.1]
 [1.2]
 [1.3]
 [1.4]
 [1.5]
 [1.6]
 [1.7]
 [1.8]
 [1.9]]
[0.     0.0475 0.095  0.1425 0.19   0.2375 0.285  0.3325 0.38   0.4275
 0.475  0.5225 0.57   0.6175 0.665  0.7125 0.76   0.8075 0.855  0.9025]
0.9025000000000001
[0.     0.0475 0.095  0.1425 0.19   0.2375 0.285  0.3325 0.38   0.4275
 0.475  0.5225 0.57   0.6175 0.665  0.7125 0.76   0.8075 0.855  0.9025]
[0.         0.02883141 0.05766281 0.08649422 0.11532563 0.14415703
 0.17298844 0.20181985 0.23065125 0.25948266 0.28831406 0.31714547
 0.34597688 0.37480828 0.40363969 0.4324711  0.4613025  0.49013391
 0.51896532 0.54779672]
[0.         0

In [22]:
rand_int = np.random.randint(5, 10, size=(3,2))
print(rand_int)
rand_uniform = np.random.uniform(size=(3,2))
print(rand_uniform)
rand_normal = np.random.normal(1., 5., size=(3,2))
print(rand_normal)

[[9 7]
 [9 6]
 [5 8]]
[[0.36378684 0.01019603]
 [0.77895517 0.50470867]
 [0.04660633 0.32551324]]
[[-2.26223794  5.9023321 ]
 [-5.04027553 -2.84724927]
 [ 3.76225554  5.13517755]]
